schema_version: 1

context:
  name: cohere
  version: 5.18.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cohere-${{ version }}.tar.gz
  sha256: 93a7753458a45cd30c796300182d22bb1889eadc510727e1de3d8342cb2bc0bf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - fastavro >=1.9.4,<2.0.0
    - httpx >=0.21.2
    - httpx-sse 0.4.0.*
    - pydantic >=1.9.2
    - pydantic-core >=2.18.2,<3.0.0
    - requests >=2.0.0,<3.0.0
    - tokenizers >=0.15,<1
    - types-requests >=2.0.0,<3.0.0
    - typing_extensions >=4.0.0

tests:
  - python:
      imports:
        - cohere
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://pypi.org/project/cohere/
  documentation: https://docs.cohere.com/
  repository: https://github.com/cohere-ai/cohere-python
  summary: |
    The Cohere Python SDK allows access to Cohere models across many different platforms: the cohere platform, AWS (Bedrock, Sagemaker), Azure, GCP and Oracle OCI. For a full list of support and snippets, please take a look at the SDK support docs page (https://docs.cohere.com/docs/cohere-works-everywhere).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shermansiu
